CREATE TABLE "TB_CLIENTES" (
	"ID" INTEGER PRIMARY KEY AUTOINCREMENT,
	"ENDERECO" TEXT NOT NULL,
	"NOME" TEXT NOT NULL
);


CREATE TABLE "TB_VENDEDORES" (
	"ID" INTEGER PRIMARY KEY AUTOINCREMENT,
	"NOME" TEXT NOT NULL
);


CREATE TABLE "TB_PRODUTOS" (
	"ID" INTEGER PRIMARY KEY AUTOINCREMENT,
	"NOME" TEXT NOT NULL, 
	"PRECO" REAL NOT NULL
);


CREATE TABLE "TB_NOTAS_FISCAIS" (
	"ID" INTEGER PRIMARY KEY AUTOINCREMENT,
	"ID_CLIENTE" INTEGER NOT NULL,
	"ID_VENDEDOR" INTEGER NOT NULL,
	"NUM_NF" INTEGER UNIQUE NOT NULL,
	"SERIE_NF" CHAR NOT NULL,
	
	FOREIGN KEY ("ID_CLIENTE") REFERENCES "TB_CLIENTES"("ID"),
	FOREIGN KEY ("ID_VENDEDOR") REFERENCES "TB_VENDEDORES"("ID")
);


CREATE TABLE "TB_ITENS_NOTAFISCAL" (
	"ID" INTEGER PRIMARY KEY AUTOINCREMENT,
	"QTD" INTEGER NOT NULL,
	"VALOR_TOTAL" INTEGER NOT NULL,
	"ID_NF" INTEGER UNIQUE NOT NULL,
	"ID_PRODUTO" INTEGER UNIQUE NOT NULL,

	FOREIGN KEY ("ID_NF") REFERENCES "TB_NOTAS_FISCAIS"("ID"),
	FOREIGN KEY ("ID_PRODUTO") REFERENCES "TB_PRODUTOS"("ID")
);


.save "NotaFiscal.bd"
